### ISSUE TITLE
Deprecated code: UserRolesAttribute.java

### ISSUE THREAD

**Issue by olegood** [olegood/boosti#44]
### Description
Since roles hierarchy implemented, no need to combine roles anymore.
Code of `UserRolesAttribute.java` could be safely removed.

**P.S.** _This approach could be used in case of permissions-based solution (YAGNI)._

### Tasks
- [x] delete unused `UserRolesAttribute`
- [x] delete unused `UserRolesAttributeTest`
- [x] delete unused `UserRolesAttributeSpec`
- [x] move `User` to `domain` package
