### ISSUE TITLE
Deprecated code: QuestionServiceImplTest#shouldReturnAllQuestions

### ISSUE THREAD

**Issue by olegood** [olegood/boosti#45]
### Description
Test case `QuestionServiceImplTest#shouldReturnAllQuestions` was fully replaced with Spock fixture `QuestionServiceImplSpec#service should return all questions from repository` in 83d659c7

Reduce time of test running: `618ms -> 107ms`

_See for details:_ 83d659c71aec76f789256853c74540b8048c7cb0

### Tasks
- [x] delete unused `QuestionServiceImplTest#shouldReturnAllQuestions`
- [x] delete unused `QuestionServiceImplTest#from(java.lang.Long, java.lang.String)`
- [x] delete unused `QuestionServiceImplTest#from(java.lang.String)`
